config/routes.rb
Rails.application.routes.draw do



  root to: 'home#index'


  resources :users, only: [:new, :create] do
    get 'show_user_biddings/index'

  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :auctions, only: [:new, :create, :index, :show] do
    resources :biddings, only: [:new, :create], shallow: :true

    resources :publishings, only: [:create]


  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  include AASM
  belongs_to :user
  has_many :biddings, dependent: :destroy

  aasm :whiny_transitions => false do

    state :draft, :initial => true

    state :published, :reserve_met, :won, :canceled, :reserve_not_met

    event :publish do
      transitions :from => :draft, :to => :published
    end

    event :above_reserve_price do
      transitions :from => :published, :to => :reserve_met
      transitions :from => :reserve_not_met, :to => :reserve_met

    end

    event :below_reserve_price do
      transitions :from => :published, :to => :reserve_not_met
    end

    event :cancel do
      transitions :from => :published, :to => :canceled
    end

    event :top_price do
      transitions :from => :reserve_met, :to => :won
    end


  end



end

app/models/bidding.rb
class Bidding < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :auctions, dependent: :destroy
  has_many :biddings, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def user_authentication

    redirect_to root_path, alert: "Please sign in first." unless user_sign_in?
  end


  private

  def user_sign_in?
    session[:user_id] ? true : false

  end

  helper_method :user_sign_in?

  def current_user
    @user||=User.find(session[:user_id]) if user_sign_in?
  end

  helper_method :current_user


end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :user_authentication, only: [:new,:create]


  def new
    @auction=Auction.new
  end

  def create
    @auction=Auction.new(auction_params)

    # transfer date from datepicker to datetime
    @auction.endon= Date.strptime(params[:auction][:endon], "%m/%d/%Y").strftime("%Y/%m/%d %H:%M:%S")

    @auction.user=current_user
    if @auction.save
      redirect_to auctions_path
    else
      redirect_to root_path
    end

  end

  def index
    @auctions=Auction.order("created_at DESC")
  end

  def show
    @auction=Auction.find(params[:id])
    @current_bidding=Bidding.new

    @biddings=Bidding.where(auction: @auction).order(created_at: :desc)


  end

  private
  def auction_params
    params.require(:auction).permit(:title, :detail, :endon, :price)
  end
end

app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  before_action :user_authentication, only: :create

  before_action :user_not_bidding_self, only: :create


  def create

    auction_id=params[:auction_id]
    @auction=Auction.find(auction_id)
    @current_bidding=Bidding.new(bidding_params)
    @current_bidding.user=current_user
    @current_bidding.auction=@auction

    # default value for previous bidding in case there is no bidding
    previous_bidding=0
    previous_bidding=@auction.biddings.last.price if @auction.biddings.last
    bidding_price=bidding_params[:price]


    if @current_bidding.price.to_i >= previous_bidding.to_i
      change_current_bidding(bidding_price)

      respond_to do |format|
        format.html {
          flash[:notice] = 'Thanks for your bidding.'
          redirect_to auction_path(auction_id)
        }
        format.json {
          render json: @current_bidding

        }
      end


    else

      respond_to do |format|
        format.html {
          flash[:alert] = 'Your bidding price should be higher than the recent price. '
          redirect_to auction_path(auction_id)
        }
        format.json {
          # render json: @user
        }
      end



    end


    # respond_to do |format|
    #   format.html {
    #
    #   }
    #   format.json {
    #     render json: @user
    #   }
    # end


  end

  def index

  end

  private
  def bidding_params
    params.require(:bidding).permit(:price)
  end

  def user_not_bidding_self
    @auction=Auction.find(params[:auction_id])

    if session[:user_id]==@auction.user.id
      redirect_to auction_path(@auction), alert: 'You can not bid yourself'
    end

    def change_status
        if @current_bidding.price.to_i >=@auction.price.to_i
          @auction.above_reserve_price
          @auction.save
        else
          @auction.below_reserve_price
          @auction.save
        end
    end

    def change_current_bidding(bidding_price)
      @current_bidding.price=bidding_price
      @current_bidding.save
      change_status
    end

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end




end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController

  def create
    id=params[:auction_id]
    auction=Auction.find(id)
      auction.publish
      auction.save


    redirect_to auction


  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user=User.find_by(email:params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to root_path, notice:"You successfuly log in"
    else
      redirect_to root_path, alert:"You failure log in"
    end

  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path,notice: "You successfuly log out"

  end

end

app/controllers/show_user_biddings_controller.rb
class ShowUserBiddingsController < ApplicationController
  before_action :user_authentication


  def index
    @user=User.find(params[:user_id])
    @biddings= @user.biddings


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new

  end

  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path

    else

    end


  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name,:email,:password)


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/biddings_helper.rb
module BiddingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publishings_helper.rb
module PublishingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/show_user_biddings_helper.rb
module ShowUserBiddingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/create.html.erb
<h1>Auctions#create</h1>
<p>Find me in app/views/auctions/create.html.erb</p>

app/views/auctions/index.html.erb
<h1>Auctions#index</h1>
<p>Find me in app/views/auctions/index.html.erb</p>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Detail</th>
    <th>Endon</th>
    <th>Price</th>
  </tr>

  <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.title %></td>
        <td><%= auction.detail %></td>
        <td><%= auction.endon %></td>
        <td><%= auction.price %></td>
        <td><%= link_to "Go to",auction_path(auction) %></td>

      </tr>


  <% end %>

</table>

app/views/auctions/new.html.erb
<h1>Auctions#new</h1>

<%= simple_form_for @auction do |f| %>
    <%= f.input :title %>
    <%= f.input :detail %>
    <%= f.input :price %>
    <%= f.input :endon, as: :string, input_html: {class: 'datepicker', 'data-provide':'datepicker'} %>
    <%= f.button :submit %>

<% end %>




<script type="text/javascript" charset="utf-8">
    $('.datepicker').datepicker();
</script>

app/views/auctions/show.html.erb
<h1>Auctions#show</h1>
<input type="hidden" id="auction_id" value=<%= @auction.id %>>



<table class="table">
  <tbody>
  <tr>
    <td>State:</td>
    <td><%= @auction.aasm_state %></td>
  </tr>

  <tr>
    <td>Title</td>
    <td><%= @auction.title %></td>
  </tr>
  <tr>
    <td>Detail</td>
    <td><%= @auction.detail %></td>
  </tr>
  <tr>
    <td>Ends on</td>
    <td><%= @auction.endon %></td>
  </tr>
  <tr>
    <td>Price:</td>
    <td><%= @auction.price %></td>
  </tr>


  </tbody>


</table>

<% if current_user && current_user.id==@auction.user.id %>
    <div>
      <%= link_to "Published", auction_publishings_path(@auction), method: :post %>
    </div>
<% end %>


<%= simple_form_for [@auction, @current_bidding] do |f| %>
<%#= simple_form_for auction_bidding_index_path(@auction) do |f|%>

    <%= f.input :price %>

    <%= f.button :submit %>

<% end %>


<div class="well">
  <p>It is a Ajax form to bid.</p>
  <form action="#" method="post">
    <input type="text" name="" id="ajax-submit-price">
    <input type="submit" value="submit" id="ajax-form-submit">

  </form>
</div>

<table class="table">
  <thead>
  <tr>
    <td></td>
    <td>Price</td>
    <td>Time</td>
    <td>User Name</td>
  </tr>
  </thead>

  <tbody id="bidding-table">

  <% @biddings.each do |bidding| %>
      <tr>
        <td>Bidding:</td>
        <td><%= bidding.price %></td>
        <td><%= bidding.created_at %></td>
        <td> <%= link_to bidding.user.name, user_show_user_biddings_index_path(bidding.user) %></td>
      </tr>
  <% end %>


  </tbody>


</table>


<script type="text/javascript" charset="utf-8">

    var DOMAIN = 'http://localhost:3000'

    var id = $('#auction_id').val();

    $('#ajax-form-submit').on('click', function (event) {
        event.preventDefault();
        price = $('#ajax-submit-price').val();
        $.post({
                url: DOMAIN + '/auctions/' + id + '/biddings.json',
                data: {
                    bidding: {price: price}

                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);

                     var bidding_node=$('<tr><td>Bidding:</td><td>' + data.price + '</td><td>' + data.created_at + '</td> <td>' + data.user_id + '</td></tr>').hide().fadeIn(1000);

                    $('#bidding-table').prepend(bidding_node);


                },
                error: function (data) {
                    console.log(data)

                }
            }
        );

    });


</script>

app/views/biddings/create.html.erb
<h1>Biddings#create</h1>
<p>Find me in app/views/biddings/create.html.erb</p>

app/views/biddings/index.html.erb
<h1>Biddings#index</h1>
<p>Find me in app/views/biddings/index.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>

<% if user_sign_in? %>
    <h1>Hi, <%= current_user.name %>,welcome back.</h1>

<% else %>
    <h1>Welcome to my Bidding page, please login first!</h1>

<% end %>
<p>It is a index page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bid</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><%= link_to 'List of Auctions', auctions_path %></li>

  <% unless user_sign_in? %>
      <li><%= link_to 'Sign up', new_user_path %></li>
      <li><%= link_to 'Sign in', new_session_path %></li>

<% end %>



  <% if user_sign_in? %>
      <li><%= link_to 'Sign out', session_path(current_user), method: :delete %></li>
      <li><%= link_to 'New Auction', new_auction_path %></li>
      <li>Hello, <%= current_user.name %></li>
  <% end %>
</ul>

<body>

<div class="alert alert-info">
  <% if flash[:notice] %>
      <%= flash[:notice] %>
  <% else %>
      <%= flash[:alert] %>

  <% end %>

</div>


<%= yield %>
</body>
</html>

app/views/show_user_biddings/index.html.erb
<h1>ShowUserBiddings#index</h1>
<p>Find me in app/views/show_user_biddings/index.html.erb</p>

<table class="table">

  <tbody>
  <% @biddings.each do |bidding| %>
      <tr>
        <td>Auction Price:<%= bidding.price %></td>
        <td>
          Auction title:<%= bidding.auction.title %></td>
      </tr>


  <% end %>
  </tbody>

</table>

app/views/users/_form.erb
<h1>Please register a new user. </h1>
<%= simple_form_for @user do |f|%>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.button :submit %>

<%end  %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render 'form' %>